version: "3"

services:
  
  secure_by_design_back:
    image: "node:14-alpine"
    container_name: secure_by_design_back
    user: 1000:1000
    working_dir: "/api"
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/api:rw,Z
